name: Workflow - Scheduled

on:
  schedule:
    # Se ejecuta cada minuto
    - cron: '* * * * *'

jobs:
  schedule_job:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Mensaje de Ejecución Programada
        run: echo "Ejecución programada"
